version: "3.9"

services:
  db:
    image: postgres:16
    container_name: smart_poultry_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_poultry
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pg_data:


