# Generated by Django 4.2.7 on 2025-07-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("pressure", "Pressure"),
                            ("light", "Light"),
                            ("motion", "Motion"),
                            ("sound", "Sound"),
                            ("air_quality", "Air Quality"),
                            ("water_level", "Water Level"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_value", models.FloatField(default=0.0)),
                ("unit", models.CharField(default="", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("calibrating", "Calibrating"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("min_threshold", models.FloatField(blank=True, null=True)),
                ("max_threshold", models.FloatField(blank=True, null=True)),
                ("last_reading", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor",
                "verbose_name_plural": "Sensors",
                "db_table": "sensors_tb",
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sensors.sensor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "verbose_name_plural": "Sensor Readings",
                "db_table": "sensor_readings_tb",
                "ordering": ["-timestamp"],
            },
        ),
    ]
