# Generated by Django 4.2.7 on 2025-07-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farmers", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("egg_sales", "Egg Sales"),
                            ("meat_sales", "Meat Sales"),
                            ("live_bird_sales", "Live Bird Sales"),
                            ("subscription", "Subscription"),
                            ("consultation", "Consultation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Income",
                "db_table": "financial_income_tb",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feed", "Feed"),
                            ("medicine", "Medicine"),
                            ("labor", "Labor"),
                            ("equipment", "Equipment"),
                            ("utilities", "Utilities"),
                            ("transport", "Transport"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "financial_expenses_tb",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "financial_budgets_tb",
            },
        ),
    ]
