# Generated by Django 4.2.7 on 2025-07-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=100)),
                ("activity_description", models.CharField(max_length=300)),
                ("activity_day", models.CharField(default="Day", max_length=10)),
                ("activity_status", models.IntegerField()),
                ("activity_frequency", models.IntegerField()),
            ],
            options={
                "verbose_name": "Activity Schedule",
                "verbose_name_plural": "Activity Schedules",
                "db_table": "activity_schedule_tb",
            },
        ),
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Activity Type",
                "verbose_name_plural": "Activity Types",
                "db_table": "activity_type_tb",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrive_date", models.DateField()),
                ("init_age", models.IntegerField()),
                ("harvest_age", models.IntegerField(default=0)),
                ("quantity", models.IntegerField()),
                ("init_weight", models.IntegerField()),
                ("batch_status", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "batches_tb",
            },
        ),
        migrations.CreateModel(
            name="BatchFeeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeding_date", models.DateField(auto_now_add=True)),
                ("feeding_amount", models.IntegerField()),
                ("status", models.IntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="batches.batch"
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Feeding",
                "verbose_name_plural": "Batch Feedings",
                "db_table": "batch_feeding_tb",
            },
        ),
        migrations.CreateModel(
            name="BatchActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_activity_date", models.DateField()),
                ("batch_activity_details", models.CharField(max_length=50)),
                ("batch_activity_cost", models.IntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="batches.batch"
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Activity",
                "verbose_name_plural": "Batch Activities",
                "db_table": "batch_activity_tb",
            },
        ),
    ]
