# Generated by Django 4.2.7 on 2025-07-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("batches", "0002_initial"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farmers.farm"
            ),
        ),
        migrations.AddField(
            model_name="activityschedule",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="batches.batch"
            ),
        ),
    ]
