# Generated by Django 4.2.7 on 2025-07-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Breed",
                "verbose_name_plural": "Breeds",
                "db_table": "breeds_tb",
            },
        ),
        migrations.CreateModel(
            name="ConditionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Condition Type",
                "verbose_name_plural": "Condition Types",
                "db_table": "condition_types_tb",
            },
        ),
        migrations.CreateModel(
            name="FoodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Food Type",
                "verbose_name_plural": "Food Types",
                "db_table": "food_types_tb",
            },
        ),
        migrations.CreateModel(
            name="BreedFeeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("breed_feed_status", models.IntegerField(default=1)),
                ("age", models.IntegerField()),
                ("frequency", models.IntegerField()),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="breeds.breed"
                    ),
                ),
                (
                    "food_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="breeds.foodtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed Feeding",
                "verbose_name_plural": "Breed Feedings",
                "db_table": "breed_feeding_tb",
            },
        ),
        migrations.CreateModel(
            name="BreedCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_min", models.IntegerField()),
                ("condition_max", models.IntegerField()),
                ("condition_status", models.IntegerField(default=1)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="breeds.breed"
                    ),
                ),
                (
                    "condition_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="breeds.conditiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed Condition",
                "verbose_name_plural": "Breed Conditions",
                "db_table": "breed_conditions",
            },
        ),
        migrations.CreateModel(
            name="BreedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("breed_activity_status", models.IntegerField(default=1)),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="batches.activitytype",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="breeds.breed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed Activity",
                "verbose_name_plural": "Breed Activities",
                "db_table": "breed_activities_tb",
            },
        ),
    ]
